### ISSUE TITLE
Back IDEA

### ISSUE THREAD

**Issue by driplo** [driplo/gemingame#6]
Pour la partie idées, je pense qu'il est plus logique de rattacher les idées aux challenge :

  /_Ideas_/

```
  Route::get('/ideas', 'IdeasController@index');
  Route::get('/ideas/new', 'IdeasController@showStore');
  Route::post('/ideas/new', 'IdeasController@store');
  Route::get('/idea/{idea}', 'IdeasController@detail');
```

->

```
Route::post('/challenge/{challenge}', 'ChallengesController@storeIdea');
Route::get('/challenge/{challenge}/{IDIdea}', 'ChallengesController@showIdea');
```

Sachant aussi que l'enregistrement des idées se fait sur la page du challegne dans une Pop-in

Qu'en pensez-vous ?
@AlexandreMontoyaYarce @AlexJoly

**Comment by AlexandreMontoyaYarce** [comment]
Alexandre Montoya vous recommande Hired !

Les plus belles entreprises Tech recrutent sur Hired: développement web, product management, data science et design. La plate-forme est entièrement gratuite pour les candidats.

Créez votre profil → ( https://hired.com/x/5zmps )

How it works:
* Complétez votre profil
* Recevez des demandes d’entretien
* Rejoignez l’entreprise qui vous correspond

Vous recevez cet email car votre contact Alexandre (alexandre.montoya.yarce@gmail.com) vous a invité(e) à créer votre profil sur Hired. Si vous ne souhaitez pas recevoir d'autres emails comme celui-ci merci de vous désinscrire ( http://track.customer.io/unsubscribe/ZNaOAgABY0BAiVaNmoPt3t-TxYjE ).

 

 

 

 

© 2018 Hired, Inc • 303 2nd St. South Tower, Suite 600, San Francisco, CA 94107

 

Désinscrire ( http://track.customer.io/unsubscribe/ZNaOAgABY0BAiVaNmoPt3t-TxYjE ).
